namespace Domen
{
    public enum Operacija
    {
        UlogujSe,
        NeuspesnaPrijava,
        UspesnaPrijava,
        VratiSvePredavace,
        GreskaUZahtevu,
        //kurs
        KreirajKurs,
        KursUspesnoKreiran,
        VratiSveKurseve,
        PretraziKurseve,
        KurseviUspesnoPronadjeni,
        VratiKurs,
        KursUspesnoNadjen,
        IzmeniKurs,
        KursUspesnoIzmenjen,
        ObrisiKurs,
        KursUspesnoObrisan,
        //ucenik
        KreirajUcenika,
        UcenikUspesnoKreiran,
        VratiSveUcenike,
        VratiUcenika,
        UcenikUspesnoNadjen,
        UceniciUspesnoPronadjeni,
        PretraziUcenike,
        IzmeniUcenika,
        UcenikUspesnoIzmenjen,
        ObrisiUcenika,
        //grupa
        UcenikUspesnoObrisan,
        KreirajGrupu,
        GrupaUspesnoKreirana,
        VratiSveGrupe,
        PretraziGrupe,
        GrupeUspesnoPronadjene,
        VratiGrupu,
        GrupaUspesnoNadjena,
        IzmeniGrupu,
        GrupaUspesnoIzmenjena,
        OdjaviZaposlenog
    }
}
