namespace Domen
{
    public enum Operacija
    {
        UlogujSe,
        NeuspesnaPrijava,
        UspesnaPrijava,
        VratiSvePredavace,
        KreirajKurs,
        KursUspesnoKreiran,
        GreskaUZahtevu,
        VratiSveKurseve,
        PretraziKurs,
        KurseviUspesnoPronadjeni,
        VratiKurs,
        KursUspesnoNadjen,
        IzmeniKurs,
        KursUspesnoIzmenjen,
        ObrisiKurs,
        KursUspesnoObrisan,
        KreirajUcenika,
        UcenikUspesnoKreiran,
        VratiSveUcenike,
        VratiUcenika,
        UcenikUspesnoNadjen,
        UceniciUspesnoPronadjeni,
        PretraziUcenika,
        IzmeniUcenika,
        UcenikUspesnoIzmenjen,
        ObrisiUcenika,
        UcenikUspesnoObrisan
    }
}
